# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: "Azure - Private Linux Canada Central Dev"

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    - script: |
       python -m venv antenv
       source antenv/bin/activate
       python -m pip install --upgrade pip
       pip install setup
       pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
     workingDirectory: $(projectRoot)
     displayName: "Install requirements"
